-- "SilkierQuartz"."QRTZ_BLOB_TRIGGERS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_BLOB_TRIGGERS";

CREATE TABLE "SilkierQuartz"."QRTZ_BLOB_TRIGGERS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"TRIGGER_NAME" varchar(150) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	"BLOB_DATA" bytea NULL,
	CONSTRAINT "QRTZ_BLOB_TRIGGERS_PK_QRTZ_BLOB_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_BLOB_TRIGGERS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_BLOB_TRIGGERS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_CALENDARS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_CALENDARS";

CREATE TABLE "SilkierQuartz"."QRTZ_CALENDARS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"CALENDAR_NAME" varchar(200) NOT NULL,
	"CALENDAR" bytea NOT NULL,
	CONSTRAINT "QRTZ_CALENDARS_PK_QRTZ_CALENDARS" PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME")
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_CALENDARS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_CALENDARS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_FIRED_TRIGGERS";

CREATE TABLE "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"ENTRY_ID" varchar(140) NOT NULL,
	"TRIGGER_NAME" varchar(150) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	"INSTANCE_NAME" varchar(200) NOT NULL,
	"FIRED_TIME" int8 NOT NULL,
	"SCHED_TIME" int8 NOT NULL,
	"PRIORITY" int4 NOT NULL,
	"STATE" varchar(16) NOT NULL,
	"JOB_NAME" varchar(150) NULL,
	"JOB_GROUP" varchar(150) NULL,
	"IS_NONCONCURRENT" bool NULL,
	"REQUESTS_RECOVERY" bool NULL,
	CONSTRAINT "QRTZ_FIRED_TRIGGERS_PK_QRTZ_FIRED_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "ENTRY_ID")
);
CREATE INDEX "QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_G_J" ON "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" USING btree ("SCHED_NAME", "JOB_GROUP", "JOB_NAME");
CREATE INDEX "QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_G_T" ON "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" USING btree ("SCHED_NAME", "TRIGGER_GROUP", "TRIGGER_NAME");
CREATE INDEX "QRTZ_FIRED_TRIGGERS_IDX_QRTZ_FT_INST_JOB_REQ_RCVRY" ON "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" USING btree ("SCHED_NAME", "INSTANCE_NAME", "REQUESTS_RECOVERY");

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_FIRED_TRIGGERS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_JOB_DETAILS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_JOB_DETAILS";

CREATE TABLE "SilkierQuartz"."QRTZ_JOB_DETAILS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"JOB_NAME" varchar(150) NOT NULL,
	"JOB_GROUP" varchar(150) NOT NULL,
	"DESCRIPTION" varchar(250) NULL,
	"JOB_CLASS_NAME" varchar(300) NOT NULL,
	"IS_DURABLE" bool NOT NULL,
	"IS_NONCONCURRENT" bool NOT NULL,
	"IS_UPDATE_DATA" bool NOT NULL,
	"REQUESTS_RECOVERY" bool NOT NULL,
	"JOB_DATA" bytea NULL,
	CONSTRAINT "QRTZ_JOB_DETAILS_PK_QRTZ_JOB_DETAILS" PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_JOB_DETAILS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_JOB_DETAILS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_LOCKS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_LOCKS";

CREATE TABLE "SilkierQuartz"."QRTZ_LOCKS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"LOCK_NAME" varchar(40) NOT NULL,
	CONSTRAINT "QRTZ_LOCKS_PK_QRTZ_LOCKS" PRIMARY KEY ("SCHED_NAME", "LOCK_NAME")
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_LOCKS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_LOCKS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_PAUSED_TRIGGER_GRPS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_PAUSED_TRIGGER_GRPS";

CREATE TABLE "SilkierQuartz"."QRTZ_PAUSED_TRIGGER_GRPS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	CONSTRAINT "QRTZ_PAUSED_TRIGGER_GRPS_PK_QRTZ_PAUSED_TRIGGER_GRPS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP")
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_PAUSED_TRIGGER_GRPS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_PAUSED_TRIGGER_GRPS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_SCHEDULER_STATE" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_SCHEDULER_STATE";

CREATE TABLE "SilkierQuartz"."QRTZ_SCHEDULER_STATE" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"INSTANCE_NAME" varchar(200) NOT NULL,
	"LAST_CHECKIN_TIME" int8 NOT NULL,
	"CHECKIN_INTERVAL" int8 NOT NULL,
	CONSTRAINT "QRTZ_SCHEDULER_STATE_PK_QRTZ_SCHEDULER_STATE" PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME")
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_SCHEDULER_STATE" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_SCHEDULER_STATE" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_TRIGGERS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_TRIGGERS";

CREATE TABLE "SilkierQuartz"."QRTZ_TRIGGERS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"TRIGGER_NAME" varchar(150) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	"JOB_NAME" varchar(150) NOT NULL,
	"JOB_GROUP" varchar(150) NOT NULL,
	"DESCRIPTION" varchar(250) NULL,
	"NEXT_FIRE_TIME" int8 NULL,
	"PREV_FIRE_TIME" int8 NULL,
	"PRIORITY" int4 NULL,
	"TRIGGER_STATE" varchar(16) NOT NULL,
	"TRIGGER_TYPE" varchar(8) NOT NULL,
	"START_TIME" int8 NOT NULL,
	"END_TIME" int8 NULL,
	"CALENDAR_NAME" varchar(200) NULL,
	"MISFIRE_INSTR" int4 NULL,
	"JOB_DATA" bytea NULL,
	CONSTRAINT "QRTZ_TRIGGERS_PK_QRTZ_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
	CONSTRAINT "FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS" FOREIGN KEY ("SCHED_NAME","JOB_NAME","JOB_GROUP") REFERENCES "SilkierQuartz"."QRTZ_JOB_DETAILS"("SCHED_NAME","JOB_NAME","JOB_GROUP")
);
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_C" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "CALENDAR_NAME");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_G_J" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "JOB_GROUP", "JOB_NAME");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_NEXT_FIRE_TIME" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "NEXT_FIRE_TIME");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "TRIGGER_STATE", "NEXT_FIRE_TIME");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME", "TRIGGER_STATE");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_NFT_ST_MISFIRE_GRP" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME", "TRIGGER_GROUP", "TRIGGER_STATE");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_N_G_STATE" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "TRIGGER_GROUP", "TRIGGER_STATE");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_N_STATE" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP", "TRIGGER_STATE");
CREATE INDEX "QRTZ_TRIGGERS_IDX_QRTZ_T_STATE" ON "SilkierQuartz"."QRTZ_TRIGGERS" USING btree ("SCHED_NAME", "TRIGGER_STATE");

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_TRIGGERS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_TRIGGERS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_CRON_TRIGGERS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_CRON_TRIGGERS";

CREATE TABLE "SilkierQuartz"."QRTZ_CRON_TRIGGERS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"TRIGGER_NAME" varchar(150) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	"CRON_EXPRESSION" varchar(120) NOT NULL,
	"TIME_ZONE_ID" varchar(80) NULL,
	CONSTRAINT "QRTZ_CRON_TRIGGERS_PK_QRTZ_CRON_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
	CONSTRAINT "FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS" FOREIGN KEY ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") REFERENCES "SilkierQuartz"."QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ON DELETE CASCADE
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_CRON_TRIGGERS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_CRON_TRIGGERS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_SIMPLE_TRIGGERS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_SIMPLE_TRIGGERS";

CREATE TABLE "SilkierQuartz"."QRTZ_SIMPLE_TRIGGERS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"TRIGGER_NAME" varchar(150) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	"REPEAT_COUNT" int4 NOT NULL,
	"REPEAT_INTERVAL" int8 NOT NULL,
	"TIMES_TRIGGERED" int4 NOT NULL,
	CONSTRAINT "QRTZ_SIMPLE_TRIGGERS_PK_QRTZ_SIMPLE_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
	CONSTRAINT "FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS" FOREIGN KEY ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") REFERENCES "SilkierQuartz"."QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ON DELETE CASCADE
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_SIMPLE_TRIGGERS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_SIMPLE_TRIGGERS" TO csbs_dev_user;


-- "SilkierQuartz"."QRTZ_SIMPROP_TRIGGERS" definition

-- Drop table

-- DROP TABLE "SilkierQuartz"."QRTZ_SIMPROP_TRIGGERS";

CREATE TABLE "SilkierQuartz"."QRTZ_SIMPROP_TRIGGERS" (
	"SCHED_NAME" varchar(120) NOT NULL,
	"TRIGGER_NAME" varchar(150) NOT NULL,
	"TRIGGER_GROUP" varchar(150) NOT NULL,
	"STR_PROP_1" varchar(512) NULL,
	"STR_PROP_2" varchar(512) NULL,
	"STR_PROP_3" varchar(512) NULL,
	"INT_PROP_1" int4 NULL,
	"INT_PROP_2" int4 NULL,
	"LONG_PROP_1" int8 NULL,
	"LONG_PROP_2" int8 NULL,
	"DEC_PROP_1" numeric(13, 4) NULL,
	"DEC_PROP_2" numeric(13, 4) NULL,
	"BOOL_PROP_1" bool NULL,
	"BOOL_PROP_2" bool NULL,
	"TIME_ZONE_ID" varchar(80) NULL,
	CONSTRAINT "QRTZ_SIMPROP_TRIGGERS_PK_QRTZ_SIMPROP_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
	CONSTRAINT "FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS" FOREIGN KEY ("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") REFERENCES "SilkierQuartz"."QRTZ_TRIGGERS"("SCHED_NAME","TRIGGER_NAME","TRIGGER_GROUP") ON DELETE CASCADE
);

-- Permissions

ALTER TABLE "SilkierQuartz"."QRTZ_SIMPROP_TRIGGERS" OWNER TO csbs_dev_user;
GRANT ALL ON TABLE "SilkierQuartz"."QRTZ_SIMPROP_TRIGGERS" TO csbs_dev_user;